### ISSUE TITLE
示例运行命令有误

### ISSUE THREAD

**Issue by wenfengand** [gota33/go-config-server#1]
应该改为如下命令
```sh
./go-config-server web -repo=https://github.com/google/jsonnet.git -user=
```
如果没有 `-user=`，会导致用户名默认为本机用户名，存在 auth，进而产生 `authentication required` 错误。

**Comment by GotaX** [comment]
@wenfengand 这个问题是因为环境变量中的 USER 和命令行配置撞车了，现在给所有的环境变量加上了 GO_CONFIG_SERVER_ 的前缀。请用 dev 分支再试一次看看，如果确认没问题我来更新到 master。

**Comment by wenfengand** [comment]
@GotaX 已确认没有问题
